"""Interactive configuration wizard for Patchbay.

``patchbay config`` (no args) runs a guided prompt sequence that writes or
updates ``.ai/patchbay.toml``.  ``patchbay config set <key> <value>`` allows
non-interactive key-value edits.  ``patchbay config --doctor`` validates the
resolved phase configuration.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import tomlkit


ECONOMY_PROFILE = {
    "profile": "economy",
    "summary": "Route high-volume implementation and repair work to the configured low-cost writer while leaving plan/review choices unchanged.",
}

CONFIG_PROFILES = {"economy": ECONOMY_PROFILE}


def _prompt(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        return input(f"{prompt}{suffix}: ").strip() or default
    except (EOFError, KeyboardInterrupt):
        print("\nConfig wizard cancelled.", file=sys.stderr)
        raise SystemExit(0) from None


def _prompt_choice(prompt: str, options: list[str], default: str = "") -> str:
    print(f"\n{prompt}")
    for i, opt in enumerate(options, 1):
        marker = " (*)" if opt == default else ""
        print(f"  {i}. {opt}{marker}")
    while True:
        try:
            raw = input(f"Choose [1-{len(options)}]" + (f" ({options.index(default) + 1})" if default in options else "") +  ": ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nConfig wizard cancelled.", file=sys.stderr)
            raise SystemExit(0) from None
        if not raw and default in options:
            return default
        try:
            idx = int(raw) - 1
            if 0 <= idx < len(options):
                return options[idx]
        except ValueError:
            pass
        print(f"Enter a number 1-{len(options)}.")


def _format_toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, list):
        items = ", ".join(f'"{item}"' for item in value)
        return f"[{items}]"
    if isinstance(value, dict):
        return "{}"
    if isinstance(value, (int, float)):
        return str(value)
    return f'"{value}"'


def _write_toml(path: Path, sections: dict[str, dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# Patchbay configuration — generated by `patchbay config`\n")
        f.write("# See docs/patchbay.md for all options.\n\n")
        for section, keys in sections.items():
            if not keys:
                continue
            _write_section(f, section, keys)
            f.write("\n")


def _write_section(f: object, section: str, keys: dict[str, Any], _depth: int = 0) -> None:
    """Write a TOML section, recursing into nested tables."""
    simple: dict[str, Any] = {}
    nested: dict[str, dict[str, Any]] = {}
    for key, value in keys.items():
        if isinstance(value, dict) and value and all(not isinstance(v, (dict, list)) for v in value.values()):
            # Nested inline table: key = { k1 = v1, k2 = v2 }
            simple[key] = value
        elif isinstance(value, dict):
            nested[key] = value
        else:
            simple[key] = value
    if simple:
        f.write(f"[{section}]\n")
        for key, value in simple.items():
            if isinstance(value, dict):
                f.write(f"{key} = {{ ")
                f.write(", ".join(f"{k} = {_format_toml_value(v)}" for k, v in value.items()))
                f.write(" }\n")
            else:
                f.write(f"{key} = {_format_toml_value(value)}\n")
    for sub_key, sub_keys in nested.items():
        _write_section(f, f"{section}.{sub_key}", sub_keys, _depth + 1)


def run_config_wizard(
    cwd: Path,
    *,
    set_key: str = "",
    set_value: str = "",
    doctor: bool = False,
    show: bool = False,
    phase: str = "",
    provider: str = "",
    model: str = "",
    command_key: str = "",
    command_key_name: str = "",
    command_value: str = "",
    test_command: str = "",
    provider_id: str = "",
    provider_roles: list[str] | None = None,
    provider_command: str = "",
    provider_args: list[str] | None = None,
    prompt_mode: str = "stdin",
    output_contract: str = "",
    profile: str = "",
    show_profile: bool = False,
) -> dict[str, Any]:
    """Entry point for ``patchbay config``.

    If *set_key* is provided, write a single key=value to the config and return.
    If *doctor* is True, validate the resolved config without writing.
    Otherwise, run the interactive wizard.
    """
    from .config import config_path, find_project_root, load_config, resolve_phase

    root = find_project_root(cwd, prefer_git=True)
    cfg = load_config(root)
    cfg_path = config_path(root)

    if show:
        return {"config": str(cfg_path), "resolved": _public_config(cfg)}

    if show_profile:
        status = _profile_status(cfg)
        return {
            "config": str(cfg_path),
            **status,
            "next_actions": _profile_next_actions(status),
            "actions": _profile_actions(status),
        }

    if profile:
        return _apply_profile(cfg_path, cfg, profile)

    if phase:
        return _set_phase(cfg_path, cfg, phase, provider=provider, model=model, command_key=command_key)

    if command_key_name:
        return _set_config_key(cfg_path, cfg, f"commands.{command_key_name}", command_value)

    if test_command:
        return _add_test_command(cfg_path, cfg, test_command)

    if provider_id or provider_roles is not None or provider_command or provider_args is not None or output_contract:
        return _add_cli_provider(
            cfg_path,
            cfg,
            provider_id=provider_id,
            roles=provider_roles or [],
            command=provider_command,
            args=provider_args or [],
            prompt_mode=prompt_mode,
            output_contract=output_contract,
        )

    if set_key:
        return _set_config_key(cfg_path, cfg, set_key, set_value)

    if doctor:
        return _run_doctor(cfg)

    return _run_wizard(cfg_path, cfg)


def _public_config(cfg: dict[str, Any]) -> dict[str, Any]:
    redacted = dict(cfg)
    redacted["env"] = "<inherited process env omitted>"
    return redacted


def _set_phase(
    cfg_path: Path,
    cfg: dict[str, Any],
    phase: str,
    *,
    provider: str,
    model: str = "",
    command_key: str = "",
) -> dict[str, Any]:
    phase_cfg: dict[str, Any] = {"provider": provider}
    if model:
        phase_cfg["model"] = model
    if command_key:
        phase_cfg["command_key"] = command_key
    cfg.setdefault("phases", {})[phase] = {**cfg.get("phases", {}).get(phase, {}), **phase_cfg}
    _write_config_update(cfg_path, ("phases", phase), phase_cfg)
    return {"config": str(cfg_path), "phase": phase, "updated": phase_cfg}


def _add_test_command(cfg_path: Path, cfg: dict[str, Any], command: str) -> dict[str, Any]:
    allowlist = cfg.setdefault("commands_allowlist", {}).setdefault("test", [])
    if command not in allowlist:
        allowlist.append(command)
    test_phase = cfg.setdefault("phases", {}).setdefault("test", {})
    commands = test_phase.setdefault("commands", [])
    if command not in commands:
        commands.append(command)
    _write_config_updates(
        cfg_path,
        [
            (("commands_allowlist", "test"), allowlist),
            (("phases", "test", "commands"), commands),
        ],
    )
    return {"config": str(cfg_path), "test_command": command, "allowlisted": True}


def _add_cli_provider(
    cfg_path: Path,
    cfg: dict[str, Any],
    *,
    provider_id: str,
    roles: list[str],
    command: str,
    args: list[str],
    prompt_mode: str,
    output_contract: str,
) -> dict[str, Any]:
    provider_id = provider_id.strip()
    roles = [str(role).strip() for role in roles if str(role).strip()]
    command = command.strip()
    prompt_mode = prompt_mode.strip()
    output_contract = output_contract.strip()
    _validate_cli_provider_input(
        provider_id=provider_id,
        roles=roles,
        command=command,
        prompt_mode=prompt_mode,
        output_contract=output_contract,
    )
    provider_cfg = {
        "roles": roles,
        "command": command,
        "args": args,
        "prompt_mode": prompt_mode,
        "output_contract": output_contract,
    }
    cfg.setdefault("providers", {})[provider_id] = provider_cfg
    _write_config_update(cfg_path, ("providers", provider_id), provider_cfg)
    return {"config": str(cfg_path), "provider": provider_id, "updated": provider_cfg}


def _validate_cli_provider_input(
    *,
    provider_id: str,
    roles: list[str],
    command: str,
    prompt_mode: str,
    output_contract: str,
) -> None:
    from .adapters import BUILTIN_PROVIDER_IDS, ROLE_FIX, ROLE_PLAN, ROLE_REVIEW, ROLE_WRITE
    from .errors import AiFlowError

    provider_id = provider_id.strip()
    if not provider_id:
        raise AiFlowError("Custom provider id cannot be empty.", stage="config")
    if provider_id in BUILTIN_PROVIDER_IDS:
        raise AiFlowError(
            f"Custom provider id collides with built-in provider: {provider_id}",
            stage="config",
            suggested_next_action="Choose a unique provider id such as cheap_writer or local_writer.",
        )
    role_set = {str(role).strip() for role in roles if str(role).strip()}
    if not role_set:
        raise AiFlowError("Custom provider must declare at least one role.", stage="config")
    valid_roles = {ROLE_PLAN, ROLE_WRITE, ROLE_REVIEW, ROLE_FIX}
    invalid_roles = role_set - valid_roles
    if invalid_roles:
        raise AiFlowError(
            f"Custom provider has invalid roles: {', '.join(sorted(invalid_roles))}",
            stage="config",
            suggested_next_action="Use one or more of: plan, write, review, fix.",
        )
    if not command.strip():
        raise AiFlowError("Custom provider command cannot be empty.", stage="config")
    if prompt_mode not in {"stdin", "arg", "file"}:
        raise AiFlowError("Custom provider prompt_mode must be one of: stdin, arg, file.", stage="config")
    if output_contract not in {"plan_json", "review_verdict", "worktree_diff", "writer_diff"}:
        raise AiFlowError(
            "Custom provider output_contract must be one of: plan_json, review_verdict, worktree_diff, writer_diff.",
            stage="config",
        )


def _economy_profile_definition(cfg: dict[str, Any]) -> dict[str, Any]:
    from .config import economy_target

    target = economy_target(cfg)
    provider = target["provider"]
    model = target["model"]
    command_key = target["command_key"]
    updates: dict[tuple[str, ...], str] = {
        ("writer", "provider"): provider,
        ("phases", "write", "provider"): provider,
        ("phases", "fix", "provider"): provider,
    }
    if model:
        updates[("models", "writer")] = model
        updates[("phases", "write", "model")] = model
        updates[("phases", "fix", "model")] = model
    if command_key:
        updates[("phases", "write", "command_key")] = command_key
        updates[("phases", "fix", "command_key")] = command_key
    return {
        "profile": "economy",
        "summary": f"Route high-volume implementation and repair work to {target['label']} while leaving plan/review choices unchanged.",
        "updates": updates,
    }


def _profile_definition(cfg: dict[str, Any], profile: str) -> dict[str, Any] | None:
    if profile == "economy":
        return _economy_profile_definition(cfg)
    return CONFIG_PROFILES.get(profile)


def _apply_profile(cfg_path: Path, cfg: dict[str, Any], profile: str) -> dict[str, Any]:
    name = profile.strip().lower()
    definition = _profile_definition(cfg, name)
    if definition is None:
        from .errors import AiFlowError
        raise AiFlowError(
            f"Unknown config profile: {profile}. Supported profiles: {', '.join(sorted(CONFIG_PROFILES))}.",
            stage="config",
            suggested_next_action="Run `patchbay config profile apply economy`.",
        )
    updates = list(definition["updates"].items())
    for parts, value in updates:
        _set_nested(cfg, parts, value)
    _write_config_updates(cfg_path, updates)
    status = _profile_status(cfg)
    economy = status.get("economy", {}) if isinstance(status.get("economy"), dict) else {}
    target = economy.get("target", {}) if isinstance(economy.get("target"), dict) else {}
    next_actions = ["Run `patchbay config --doctor --json` to validate the resolved routing."]
    if target.get("provider") == "reasonix_cli":
        next_actions.insert(0, "Set `commands.reasonix` if Reasonix is not on PATH.")
    return {
        "config": str(cfg_path),
        "profile": name,
        "summary": definition["summary"],
        "updated": {
            ".".join(parts): value for parts, value in updates
        },
        "status": status,
        "next_actions": next_actions,
        "actions": _profile_actions(status, include_validate=True),
    }


def _profile_next_actions(status: dict[str, Any]) -> list[str]:
    profile = status.get("profile")
    if profile == "economy":
        economy = status.get("economy", {}) if isinstance(status.get("economy"), dict) else {}
        if economy.get("command_ready") is False:
            target = economy.get("target", {}) if isinstance(economy.get("target"), dict) else {}
            if target.get("provider") == "reasonix_cli":
                return ["configure reasonix command", "readiness"]
        return ["readiness", "start"]
    if profile == "custom":
        return ["apply economy profile", "readiness"]
    return ["readiness"]


def _profile_actions(status: dict[str, Any], *, include_validate: bool = False) -> list[dict[str, Any]]:
    actions: list[dict[str, Any]]
    profile = status.get("profile")
    if profile == "economy":
        actions = [
            {
                "id": "open_readiness",
                "label": "Open readiness",
                "kind": "local_agent",
                "message": "readiness",
                "safe": True,
                "reason": "Inspect setup and resolved write/fix routing.",
            },
        ]
        economy = status.get("economy", {}) if isinstance(status.get("economy"), dict) else {}
        if economy.get("command_ready") is False:
            target = economy.get("target", {}) if isinstance(economy.get("target"), dict) else {}
            if target.get("provider") == "reasonix_cli":
                actions.append(_configure_reasonix_action(str(target.get("label") or "Reasonix/DeepSeek")))
            else:
                actions.append(
                    {
                        "id": "inspect_economy_provider_command",
                        "label": "Inspect provider command",
                        "kind": "local_agent",
                        "message": "readiness",
                        "safe": True,
                        "reason": "Inspect the command or provider setup for the configured economy target.",
                    }
                )
        else:
            actions.append(
                {
                    "id": "start_new_task",
                    "label": "Start new task",
                    "kind": "focus_composer",
                    "safe": True,
                    "reason": "Start a new Patchbay plan using the active economy routing profile.",
                }
            )
    elif profile == "custom":
        actions = [
            {
                "id": "apply_economy_profile",
                "label": "Apply economy profile",
                "kind": "local_agent",
                "message": "apply economy profile",
                "safe": True,
                "reason": "Route high-volume write/fix work to the configured economy profile.",
            },
            {
                "id": "open_readiness",
                "label": "Open readiness",
                "kind": "local_agent",
                "message": "readiness",
                "safe": True,
                "reason": "Inspect setup and current routing before changing the profile.",
            },
        ]
    else:
        actions = [
            {
                "id": "open_readiness",
                "label": "Open readiness",
                "kind": "local_agent",
                "message": "readiness",
                "safe": True,
                "reason": "Inspect setup and phase configuration errors before changing routing.",
            }
        ]
    if include_validate:
        actions.append(
            {
                "id": "validate_config",
                "label": "Validate config",
                "kind": "command",
                "command": "patchbay config --doctor --json",
                "safe": True,
                "reason": "Validate resolved phase routing after applying the profile.",
            }
        )
    return actions


def _configure_reasonix_action(target_label: str = "Reasonix/DeepSeek") -> dict[str, Any]:
    return {
        "id": "configure_reasonix_command",
        "label": "Configure Reasonix",
        "kind": "local_agent",
        "message": "configure reasonix command",
        "command": "patchbay config --set-key commands.reasonix --set-value reasonix",
        "safe": True,
        "reason": f"Set the default Reasonix executable so the {target_label} write/fix economy route can actually run.",
    }


def _set_nested(cfg: dict[str, Any], parts: tuple[str, ...], value: Any) -> None:
    current: Any = cfg
    for part in parts[:-1]:
        current = current.setdefault(part, {})
    current[parts[-1]] = value


def _profile_status(cfg: dict[str, Any]) -> dict[str, Any]:
    from .config import economy_target, resolve_phase, route_matches_economy

    target = economy_target(cfg)
    try:
        write = _public_phase(resolve_phase(cfg, "write"))
        fix = _public_phase(resolve_phase(cfg, "fix"))
    except Exception as exc:
        return {
            "profile": "invalid",
            "economy": {"matches": False, "error": str(exc)},
            "recommendation": "Fix phase configuration errors before applying a routing profile.",
        }
    economy_matches = (
        route_matches_economy(write, target)
        and route_matches_economy(fix, target)
    )
    command_status = {
        "write": _phase_command_status(cfg, write),
        "fix": _phase_command_status(cfg, fix),
    }
    command_ready = all(
        item.get("ready") for item in command_status.values() if item.get("required")
    )
    return {
        "profile": "economy" if economy_matches else "custom",
        "economy": {
            "matches": economy_matches,
            "target": target,
            "write": write,
            "fix": fix,
            "command_ready": command_ready,
            "command_status": command_status,
            "intent": f"High-volume write/fix work runs on the configured low-cost {target['label']} route.",
        },
        "phase_strategy": _phase_strategy(cfg),
        "recommendation": ""
        if economy_matches
        else f"Run `patchbay config profile apply economy` to route write/fix work to {target['label']}.",
    }


def _phase_strategy(cfg: dict[str, Any]) -> dict[str, Any]:
    from .config import economy_target, resolve_phase, route_matches_economy

    target = economy_target(cfg)
    roles = {
        "plan": ("supervision", "Use a stronger model for task decomposition, constraints, and the execution plan."),
        "write": ("economy", "Route high-volume implementation work to the low-cost writer."),
        "fix": ("economy", "Route iterative repair work to the low-cost writer."),
        "review": ("supervision", "Use an independent stronger reviewer before apply."),
    }
    strategy: dict[str, Any] = {}
    for phase, (tier, reason) in roles.items():
        try:
            resolved = _public_phase(resolve_phase(cfg, phase))
            strategy[phase] = {
                **resolved,
                "tier": tier,
                "reason": reason,
                "economy_route": route_matches_economy(resolved, target),
            }
            command_status = _phase_command_status(cfg, resolved)
            if command_status.get("required"):
                strategy[phase]["command_status"] = command_status
        except Exception as exc:
            strategy[phase] = {"tier": tier, "reason": reason, "error": str(exc)}
    return strategy


def _phase_command_status(cfg: dict[str, Any], phase: dict[str, Any]) -> dict[str, Any]:
    from .config import route_command_status

    return route_command_status(cfg, phase)


def _public_phase(phase: dict[str, Any]) -> dict[str, Any]:
    return {
        "provider": phase.get("provider", ""),
        "model": phase.get("model", ""),
        "command_key": phase.get("command_key", ""),
        "timeout": phase.get("timeout", 900),
    }


def _set_config_key(cfg_path: Path, cfg: dict[str, Any], key: str, value: str) -> dict[str, Any]:
    """Non-interactive set of a single config key."""
    parts = key.split(".")
    if len(parts) < 2:
        from .errors import AiFlowError
        raise AiFlowError(
            "Config keys must be in dotted form, e.g. 'models.planner' or 'phases.plan.provider'.",
            stage="config",
        )

    # Try to cast value
    typed_value: Any = value
    if value.lower() in ("true", "false"):
        typed_value = value.lower() == "true"
    elif value.isdigit():
        typed_value = int(value)

    # Navigate to the nested dict
    current: Any = cfg
    for part in parts[:-1]:
        if part not in current:
            current[part] = {}
        current = current[part]
    current[parts[-1]] = typed_value

    _write_config_update(cfg_path, tuple(parts), typed_value)
    return {"config": str(cfg_path), "set": {key: typed_value}}


def _run_doctor(cfg: dict[str, Any]) -> dict[str, Any]:
    """Validate that every configured phase resolves without error."""
    from .config import resolve_phase

    results: dict[str, Any] = {}
    for phase in ("plan", "write", "review", "fix", "test", "apply"):
        try:
            resolved = resolve_phase(cfg, phase)
            results[phase] = {
                "provider": resolved.get("provider", ""),
                "model": resolved.get("model", ""),
                "command_key": resolved.get("command_key", ""),
                "timeout": resolved.get("timeout", 900),
            }
        except Exception as exc:
            results[phase] = {"error": str(exc)}

    # Check that at least one test command is defined or auto-detect works
    test_commands = cfg.get("test", {}).get("commands", [])
    test_phase_commands = cfg.get("phases", {}).get("test", {}).get("commands", [])
    if not test_commands and not test_phase_commands:
        allowlist = cfg.get("commands_allowlist", {}).get("test", [])
        if not allowlist:
            results["_warnings"] = ["No test commands configured and commands_allowlist.test is empty."]

    return {"phases": results, "config_valid": all("error" not in v for v in results.values() if isinstance(v, dict))}


def _run_wizard(cfg_path: Path, cfg: dict[str, Any]) -> dict[str, Any]:
    """Interactive config wizard."""
    print("\n=== Patchbay Configuration Wizard ===\n")
    print("This wizard will help you create or update .ai/patchbay.toml.\n")

    # --- Provider selection ---
    print("--- Provider Setup ---\n")

    plan_provider = _prompt_choice(
        "Planner provider:",
        ["claude_cli", "codex_cli", "gemini_cli", "mock"],
        default="claude_cli",
    )
    write_provider = _prompt_choice(
        "Writer provider:",
        ["reasonix_cli", "mock"],
        default="reasonix_cli",
    )
    review_provider = _prompt_choice(
        "Reviewer provider:",
        ["codex_cli", "claude_cli", "gemini_cli", "mock"],
        default="codex_cli",
    )

    # --- Model selection ---
    print("\n--- Model Setup ---\n")

    plan_model = _prompt("Planner model", default="claude-opus-4-7")
    write_model = _prompt("Writer model", default="deepseek-v4-pro")
    review_model = _prompt("Reviewer model", default="gpt-5.5")

    # --- CLI commands ---
    print("\n--- CLI Command Paths ---\n")
    print("Leave blank if the tool is not installed or you use mock mode.\n")

    claude_cmd = _prompt("claude command", default="claude")
    codex_cmd = _prompt("codex command", default="codex")
    gemini_cmd = _prompt("gemini command", default="gemini")
    reasonix_cmd = _prompt("reasonix command (for reasonix_cli writer)", default="")

    # --- Test commands ---
    print("\n--- Test Commands ---\n")
    print("Enter one command per line. Blank line to finish.\n")

    test_commands: list[str] = []
    while True:
        try:
            cmd = input(f"  Test command #{len(test_commands) + 1}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            break
        if not cmd:
            break
        test_commands.append(cmd)

    # --- Workflow settings ---
    print("\n--- Workflow ---\n")

    require_approval = _prompt_choice(
        "Require plan approval before write?",
        ["yes", "no"],
        default="yes",
    )

    # Build TOML sections
    sections: dict[str, dict[str, Any]] = {
        "models": {
            "planner": plan_model,
            "writer": write_model,
            "reviewer": review_model,
        },
        "commands": {
            "claude": claude_cmd,
            "codex": codex_cmd,
            "gemini": gemini_cmd,
            "reasonix": reasonix_cmd,
        },
        "phases": {
            "plan": {"provider": plan_provider, "model": plan_model},
            "write": {"provider": write_provider, "model": write_model},
            "review": {"provider": review_provider, "model": review_model},
            "fix": {},
            "test": {"commands": test_commands, "timeout": 900},
            "apply": {},
        },
        "workflow": {
            "require_plan_approval": require_approval == "yes",
        },
        "commands_allowlist": {
            "test": test_commands if test_commands else [
                "npm test", "npm run test", "npm run lint", "npm run typecheck",
                "pytest", "pytest -q", "go test ./...", "cargo test",
            ],
        },
    }

    _write_toml(cfg_path, sections)

    print(f"\nConfiguration written to {cfg_path}\n")
    print("Review it and adjust as needed. Run `patchbay doctor` to validate.\n")

    return {"config": str(cfg_path), "wizard": "complete"}


def _write_config(cfg_path: Path, cfg: dict[str, Any]) -> None:
    """Write a full config dict back to TOML using minimal formatting."""
    sections: dict[str, dict[str, Any]] = {}
    top_level: dict[str, Any] = {}
    for key, value in cfg.items():
        if isinstance(value, dict):
            if key in {"phases", "providers"}:
                for phase_name, phase_cfg in value.items():
                    if phase_cfg:
                        sections[f"{key}.{phase_name}"] = dict(phase_cfg)
            else:
                sections[key] = dict(value)
        else:
            top_level[key] = value

    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    with cfg_path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# Patchbay configuration\n\n")
        for k, v in top_level.items():
            f.write(f"{k} = {_format_toml_value(v)}\n")
        if top_level:
            f.write("\n")
        for section, keys in sections.items():
            if not keys:
                continue
            _write_section(f, section, keys)
            f.write("\n")


def _load_toml_document(cfg_path: Path) -> Any:
    if cfg_path.exists():
        return tomlkit.parse(cfg_path.read_text(encoding="utf-8"))
    document = tomlkit.document()
    document.add(tomlkit.comment("Patchbay configuration"))
    return document


def _to_toml_value(value: Any) -> Any:
    if isinstance(value, dict):
        table = tomlkit.table()
        for key, item in value.items():
            table[str(key)] = _to_toml_value(item)
        return table
    if isinstance(value, list):
        array = tomlkit.array()
        array.multiline(False)
        for item in value:
            array.append(_to_toml_value(item))
        return array
    return value


def _ensure_table(parent: Any, key: str) -> Any:
    existing = parent.get(key)
    if existing is None or not hasattr(existing, "items"):
        parent[key] = tomlkit.table()
    return parent[key]


def _write_config_update(cfg_path: Path, parts: tuple[str, ...], value: Any) -> None:
    _write_config_updates(cfg_path, [(parts, value)])


def _write_config_updates(cfg_path: Path, updates: list[tuple[tuple[str, ...], Any]]) -> None:
    """Apply TOML updates through tomlkit so comments and ordering survive."""
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    document = _load_toml_document(cfg_path)
    for parts, value in updates:
        current = document
        for part in parts[:-1]:
            current = _ensure_table(current, part)
        current[parts[-1]] = _to_toml_value(value)
    cfg_path.write_text(tomlkit.dumps(document), encoding="utf-8", newline="\n")
