from __future__ import annotations

from pathlib import Path


def _escape_patch_line(line: str) -> str:
    if line.startswith("\\"):
        return "\\" + line
    return line


def _new_file_diff(path: str, content: str) -> str:
    lines = content.splitlines()
    body = "\n".join("+" + _escape_patch_line(line) for line in lines)
    if body:
        body += "\n"
    return "\n".join(
        [
            f"diff --git a/{path} b/{path}",
            "new file mode 100644",
            "index 0000000..1111111",
            "--- /dev/null",
            f"+++ b/{path}",
            f"@@ -0,0 +1,{len(lines)} @@",
            body.rstrip("\n"),
        ]
    ).rstrip() + "\n"


def run_mock_writer(*, task: str, repair: bool = False, iteration: int = 0) -> str:
    path = "AI_FLOW_MOCK_OUTPUT.md" if not repair else f"AI_FLOW_MOCK_FIX_{iteration + 1}.md"
    title = "Mock Implementation" if not repair else "Mock Repair"
    content = "\n".join(
        [
            f"# {title}",
            "",
            f"Task: {task}",
            "",
            "Generated by ai-flow mock mode.",
        ]
    ) + "\n"
    diff = _new_file_diff(path, content)
    return "\n".join(
        [
            "BEGIN_WRITER_SUMMARY",
            (
                f"{title} created `{path}`."
                if not repair
                else f"{title} created `{path}` as an explicit repair artifact for the requested fix iteration."
            ),
            "END_WRITER_SUMMARY",
            "",
            "BEGIN_DIFF",
            diff.rstrip(),
            "END_DIFF",
        ]
    ) + "\n"
